// Generate mock data for WC Result and Change Log sheets
import * as ExcelJS from 'exceljs';
import * as path from 'path';

async function generateMockExcelData() {
  const workbook = new ExcelJS.Workbook();

  // ============================================
  // SHEET 1: WC RESULT (Historical Flagged Cases)
  // ============================================
  const wcResultSheet = workbook.addWorksheet('WC Result');

  // Define columns for WC Result
  wcResultSheet.columns = [
    { header: 'ROLE', key: 'role', width: 15 },
    { header: 'CRM_REF', key: 'crm_ref', width: 15 },
    { header: 'WC1_REF', key: 'wc1_ref', width: 20 },
    { header: 'CRM_TYPE', key: 'crm_type', width: 15 },
    { header: 'CRM_SUBTYPE', key: 'crm_subtype', width: 15 },
    { header: 'WC1_TYPE', key: 'wc1_type', width: 15 },
    { header: 'CRM_NAME', key: 'crm_name', width: 25 },
    { header: 'WC1_NAME', key: 'wc1_name', width: 25 },
    { header: 'WC1_MATCH_TERM', key: 'wc1_match_term', width: 25 },
    { header: 'CRM_GENDER', key: 'crm_gender', width: 12 },
    { header: 'WC1_GENDER', key: 'wc1_gender', width: 12 },
    { header: 'CRM_BIRTH_DATE', key: 'crm_birth_date', width: 15 },
    { header: 'WC1_BIRTH_DATE', key: 'wc1_birth_date', width: 15 },
    { header: 'CRM_LOCATION', key: 'crm_location', width: 20 },
    { header: 'WC1_LOCATION', key: 'wc1_location', width: 20 },
    { header: 'CRM_BIRTH_PLACE', key: 'crm_birth_place', width: 20 },
    { header: 'WC1_BIRTH_PLACE', key: 'wc1_birth_place', width: 20 },
    { header: 'CRM_NATIONALITY', key: 'crm_nationality', width: 18 },
    { header: 'WC1_NATIONALITY', key: 'wc1_nationality', width: 18 },
    { header: 'CRM_STATUS', key: 'crm_status', width: 15 },
    { header: 'CRM_STATUS_REASON', key: 'crm_status_reason', width: 25 },
    { header: 'CATEGORIES', key: 'categories', width: 30 },
    { header: 'BIOGRAPHY', key: 'biography', width: 50 },
    { header: 'MATCH_STRENGTH', key: 'match_strength', width: 15 },
    { header: 'MATCH_SCORE', key: 'match_score', width: 12 },
    { header: 'IDENTIFICATION', key: 'identification', width: 25 },
    { header: 'REPORTS', key: 'reports', width: 40 },
    { header: 'CREATION_DATE', key: 'creation_date', width: 15 },
    { header: 'MODIFICATION_DATE', key: 'modification_date', width: 15 },
    { header: 'PEP_NAME', key: 'pep_name', width: 25 },
    { header: 'PEP_CREATION_DATE', key: 'pep_creation_date', width: 15 },
    { header: 'ADDRESSES', key: 'addresses', width: 40 },
    { header: 'ASSOCIATES', key: 'associates', width: 30 },
    { header: 'ASSOCIATES_EXT', key: 'associates_ext', width: 30 },
    { header: 'PROVIDER_TYPES', key: 'provider_types', width: 20 },
    { header: 'SOURCES', key: 'sources', width: 30 },
  ];

  // Mock WC Result Data (Historical Flagged Cases)
  const wcResultData = [
    {
      role: 'Customer',
      crm_ref: 'KC-001',
      wc1_ref: 'e_tr_wco_11220089',
      crm_type: 'Individual',
      crm_subtype: 'Retail',
      wc1_type: 'PEP',
      crm_name: 'Ahmad Al-Mansour',
      wc1_name: 'Ahmad Al Mansour',
      wc1_match_term: 'Ahmad Al-Mansour',
      crm_gender: 'Male',
      wc1_gender: 'Male',
      crm_birth_date: '1975-03-15',
      wc1_birth_date: '1975-03-15',
      crm_location: 'Kuwait City, Kuwait',
      wc1_location: 'Kuwait',
      crm_birth_place: 'Kuwait City',
      wc1_birth_place: 'Kuwait',
      crm_nationality: 'Kuwaiti',
      wc1_nationality: 'Kuwait',
      crm_status: 'Active',
      crm_status_reason: 'PEP - Government Official',
      categories: 'PEP, Sanctions, Adverse Media',
      biography: 'Former government official with financial sector connections. Subject to enhanced due diligence.',
      match_strength: 'STRONG',
      match_score: '98',
      identification: 'Passport: K1234567',
      reports: 'Media Report: Financial Times 2024-11-15; Government Database Entry',
      creation_date: '2025-01-01',
      modification_date: '2026-01-03',
      pep_name: 'Ahmad Al-Mansour',
      pep_creation_date: '2024-12-01',
      addresses: 'P.O. Box 12345, Kuwait City, Kuwait; Office: Financial District Tower',
      associates: 'Mohammed Al-Rashid (Business Partner)',
      associates_ext: 'Al-Mansour Holdings Ltd (Director)',
      provider_types: 'World-Check, OFAC',
      sources: 'Government Records, Media Reports, Sanctions Lists',
    },
    {
      role: 'Vendor',
      crm_ref: 'KC-042',
      wc1_ref: 'e_tr_wco_22334455',
      crm_type: 'Entity',
      crm_subtype: 'Corporate',
      wc1_type: 'Sanctions',
      crm_name: 'Global Trade Holdings',
      wc1_name: 'Global Trade Holdings LLC',
      wc1_match_term: 'Global Trade Holdings',
      crm_gender: 'N/A',
      wc1_gender: 'N/A',
      crm_birth_date: '2010-06-20',
      wc1_birth_date: '2010-06-20',
      crm_location: 'Dubai, UAE',
      wc1_location: 'United Arab Emirates',
      crm_birth_place: 'Dubai',
      wc1_birth_place: 'UAE',
      crm_nationality: 'UAE',
      wc1_nationality: 'United Arab Emirates',
      crm_status: 'Flagged',
      crm_status_reason: 'Sanctions List - OFAC',
      categories: 'Sanctions, Money Laundering Risk',
      biography: 'Entity flagged for suspected links to sanctioned entities. Multiple shell companies registered under same address.',
      match_strength: 'VERY_STRONG',
      match_score: '99',
      identification: 'Registration No: UAE-987654',
      reports: 'OFAC SDN List Entry 2025-12-10; Financial Intelligence Unit Report',
      creation_date: '2025-11-20',
      modification_date: '2026-01-02',
      pep_name: 'N/A',
      pep_creation_date: 'N/A',
      addresses: 'Trade Center Building, Dubai; Shell Address: P.O. Box 99999',
      associates: 'Ahmed Hassan (Director), Farah Trading Co (Related Entity)',
      associates_ext: 'Network of 15+ related entities',
      provider_types: 'OFAC, EU Sanctions, World-Check',
      sources: 'OFAC SDN List, EU Sanctions Database, Company Registry',
    },
    {
      role: 'Customer',
      crm_ref: 'KC-015',
      wc1_ref: 'e_tr_wco_33445566',
      crm_type: 'Individual',
      crm_subtype: 'Private Banking',
      wc1_type: 'PEP',
      crm_name: 'Fatima Al-Sabah',
      wc1_name: 'Fatima Al Sabah',
      wc1_match_term: 'Fatima Al-Sabah',
      crm_gender: 'Female',
      wc1_gender: 'Female',
      crm_birth_date: '1982-09-10',
      wc1_birth_date: '1982-09-10',
      crm_location: 'Kuwait City, Kuwait',
      wc1_location: 'Kuwait',
      crm_birth_place: 'Kuwait City',
      wc1_birth_place: 'Kuwait',
      crm_nationality: 'Kuwaiti',
      wc1_nationality: 'Kuwait',
      crm_status: 'Under Review',
      crm_status_reason: 'PEP Family Member',
      categories: 'PEP, High Net Worth',
      biography: 'Family member of prominent political figure. Enhanced due diligence required for all transactions.',
      match_strength: 'STRONG',
      match_score: '96',
      identification: 'Passport: K9876543',
      reports: 'KYC Enhanced Due Diligence Report 2025-12-01',
      creation_date: '2025-10-15',
      modification_date: '2026-01-04',
      pep_name: 'Al-Sabah Family (Political)',
      pep_creation_date: '2024-11-01',
      addresses: 'Residential: Al-Salam District, Kuwait City',
      associates: 'Abdullah Al-Sabah (Relative)',
      associates_ext: 'Multiple family business interests',
      provider_types: 'World-Check, PEP Database',
      sources: 'Government Records, Family Tree Database',
    },
    {
      role: 'Customer',
      crm_ref: 'KC-073',
      wc1_ref: 'e_tr_wco_44556677',
      crm_type: 'Individual',
      crm_subtype: 'Retail',
      wc1_type: 'Adverse Media',
      crm_name: 'Mohammed Ibrahim',
      wc1_name: 'Mohammed Ibrahim Al-Hashimi',
      wc1_match_term: 'Mohammed Ibrahim',
      crm_gender: 'Male',
      wc1_gender: 'Male',
      crm_birth_date: '1988-05-22',
      wc1_birth_date: '1988-05-20',
      crm_location: 'Riyadh, Saudi Arabia',
      wc1_location: 'Saudi Arabia',
      crm_birth_place: 'Riyadh',
      wc1_birth_place: 'Riyadh',
      crm_nationality: 'Saudi',
      wc1_nationality: 'Saudi Arabia',
      crm_status: 'Flagged',
      crm_status_reason: 'Adverse Media - Financial Fraud',
      categories: 'Adverse Media, Financial Crime',
      biography: 'Subject of media reports alleging involvement in financial fraud scheme. Multiple lawsuits pending.',
      match_strength: 'MEDIUM',
      match_score: '82',
      identification: 'ID: SA-123456789',
      reports: 'Arab News 2025-11-25: Fraud Investigation; Reuters 2025-12-02',
      creation_date: '2025-11-28',
      modification_date: '2026-01-03',
      pep_name: 'N/A',
      pep_creation_date: 'N/A',
      addresses: 'Riyadh Business District, Building 45',
      associates: 'Investment Group Associates',
      associates_ext: 'Previously associated with 3 dissolved companies',
      provider_types: 'Adverse Media Screening, LexisNexis',
      sources: 'Media Reports, Court Records',
    },
    {
      role: 'Vendor',
      crm_ref: 'KC-029',
      wc1_ref: 'e_tr_wco_55667788',
      crm_type: 'Entity',
      crm_subtype: 'Corporate',
      wc1_type: 'Sanctions',
      crm_name: 'Mideast Supplies Co',
      wc1_name: 'Middle East Supplies Company',
      wc1_match_term: 'Mideast Supplies',
      crm_gender: 'N/A',
      wc1_gender: 'N/A',
      crm_birth_date: '2015-03-10',
      wc1_birth_date: '2015-03-10',
      crm_location: 'Beirut, Lebanon',
      wc1_location: 'Lebanon',
      crm_birth_place: 'Beirut',
      wc1_birth_place: 'Lebanon',
      crm_nationality: 'Lebanese',
      wc1_nationality: 'Lebanon',
      crm_status: 'Suspended',
      crm_status_reason: 'EU Sanctions List',
      categories: 'Sanctions, Proliferation Financing',
      biography: 'Entity designated on EU sanctions list for alleged involvement in arms trade and sanctions evasion.',
      match_strength: 'VERY_STRONG',
      match_score: '97',
      identification: 'Registration No: LB-554433',
      reports: 'EU Council Regulation 2025-10-15; UNSCR Report',
      creation_date: '2025-10-20',
      modification_date: '2026-01-02',
      pep_name: 'N/A',
      pep_creation_date: 'N/A',
      addresses: 'Industrial Zone, Beirut Port Area',
      associates: 'Hassan Nasrallah Trading (Related Entity)',
      associates_ext: 'Network flagged by FATF',
      provider_types: 'EU Sanctions, UN Sanctions, World-Check',
      sources: 'EU Council, UNSCR, Financial Intelligence',
    },
  ];

  wcResultData.forEach((row) => wcResultSheet.addRow(row));

  // Style header row
  wcResultSheet.getRow(1).font = { bold: true };
  wcResultSheet.getRow(1).fill = {
    type: 'pattern',
    pattern: 'solid',
    fgColor: { argb: 'FF0B5394' },
  };
  wcResultSheet.getRow(1).font = { bold: true, color: { argb: 'FFFFFFFF' } };

  // ============================================
  // SHEET 2: CHANGE LOG (Cases for Review)
  // ============================================
  const changeLogSheet = workbook.addWorksheet('Change Log');

  // Define columns for Change Log
  changeLogSheet.columns = [
    { header: 'CRM_REFERENCE', key: 'crm_reference', width: 15 },
    { header: 'WC1_REF', key: 'wc1_ref', width: 20 },
    { header: 'CRM_NAME', key: 'crm_name', width: 25 },
    { header: 'PRIMARY_NAME', key: 'primary_name', width: 25 },
    { header: 'MATCH_SCORE', key: 'match_score', width: 12 },
    { header: 'MATCH_STRENGTH', key: 'match_strength', width: 15 },
    { header: 'CHANGE_TYPE', key: 'change_type', width: 15 },
    { header: 'CHANGE_FIELD', key: 'change_field', width: 20 },
    { header: 'FROM_VAL', key: 'from_val', width: 20 },
    { header: 'TO_VAL', key: 'to_val', width: 20 },
    { header: 'RECORD_DATE', key: 'record_date', width: 15 },
  ];

  // Mock Change Log Data (New Cases for Review)
  const changeLogData = [
    {
      crm_reference: '123456',
      wc1_ref: 'e_tr_wco_11220089',
      crm_name: 'Ahmad holding co',
      primary_name: 'Ahmad holding co',
      match_score: '99',
      match_strength: 'STRONG',
      change_type: 'update',
      change_field: 'address',
      from_val: '2025-12-12',
      to_val: '2026-02-01',
      record_date: '03/01/2026',
    },
    {
      crm_reference: '234567',
      wc1_ref: 'e_tr_wco_22334455',
      crm_name: 'Khalid Investment Group',
      primary_name: 'Khalid Investment Group LLC',
      match_score: '87',
      match_strength: 'MEDIUM',
      change_type: 'new',
      change_field: 'entity_type',
      from_val: 'N/A',
      to_val: '2026-01-15',
      record_date: '04/01/2026',
    },
    {
      crm_reference: '345678',
      wc1_ref: 'e_tr_wco_33445566',
      crm_name: 'Sarah Al-Mutawa',
      primary_name: 'Sarah Abdullah Al-Mutawa',
      match_score: '92',
      match_strength: 'STRONG',
      change_type: 'update',
      change_field: 'nationality',
      from_val: '2025-11-20',
      to_val: '2026-01-05',
      record_date: '05/01/2026',
    },
    {
      crm_reference: '456789',
      wc1_ref: 'e_tr_wco_44556677',
      crm_name: 'Abdullah Trading Co',
      primary_name: 'Abdullah Trading Company',
      match_score: '78',
      match_strength: 'WEAK',
      change_type: 'update',
      change_field: 'registration',
      from_val: '2025-10-01',
      to_val: '2026-01-02',
      record_date: '02/01/2026',
    },
    {
      crm_reference: '567890',
      wc1_ref: 'e_tr_wco_55667788',
      crm_name: 'Noor Financial Services',
      primary_name: 'Noor Financial Services Ltd',
      match_score: '95',
      match_strength: 'VERY_STRONG',
      change_type: 'new',
      change_field: 'sanctions_status',
      from_val: 'N/A',
      to_val: '2026-01-03',
      record_date: '03/01/2026',
    },
    {
      crm_reference: '678901',
      wc1_ref: 'e_tr_wco_66778899',
      crm_name: 'Yousef Al-Salem',
      primary_name: 'Yousef Mohammed Al-Salem',
      match_score: '89',
      match_strength: 'STRONG',
      change_type: 'update',
      change_field: 'pep_status',
      from_val: '2025-12-01',
      to_val: '2026-01-04',
      record_date: '04/01/2026',
    },
    {
      crm_reference: '789012',
      wc1_ref: 'e_tr_wco_77889900',
      crm_name: 'Gulf Enterprises',
      primary_name: 'Gulf Enterprises Holdings',
      match_score: '84',
      match_strength: 'MEDIUM',
      change_type: 'update',
      change_field: 'ownership',
      from_val: '2025-11-15',
      to_val: '2026-01-01',
      record_date: '01/01/2026',
    },
    {
      crm_reference: '890123',
      wc1_ref: 'e_tr_wco_88990011',
      crm_name: 'Layla Al-Rashid',
      primary_name: 'Layla Hassan Al-Rashid',
      match_score: '91',
      match_strength: 'STRONG',
      change_type: 'new',
      change_field: 'adverse_media',
      from_val: 'N/A',
      to_val: '2026-01-04',
      record_date: '04/01/2026',
    },
    {
      crm_reference: '901234',
      wc1_ref: 'e_tr_wco_99001122',
      crm_name: 'Coastal Development Ltd',
      primary_name: 'Coastal Development Limited',
      match_score: '76',
      match_strength: 'WEAK',
      change_type: 'update',
      change_field: 'address',
      from_val: '2025-09-10',
      to_val: '2025-12-30',
      record_date: '30/12/2025',
    },
    {
      crm_reference: '012345',
      wc1_ref: 'e_tr_wco_00112233',
      crm_name: 'Hassan Al-Dhaheri',
      primary_name: 'Hassan Ahmed Al-Dhaheri',
      match_score: '93',
      match_strength: 'STRONG',
      change_type: 'new',
      change_field: 'sanctions_list',
      from_val: 'N/A',
      to_val: '2026-01-05',
      record_date: '05/01/2026',
    },
    {
      crm_reference: '112233',
      wc1_ref: 'e_tr_wco_11223344',
      crm_name: 'Reem Investment Group',
      primary_name: 'Reem Investment Group LLC',
      match_score: '88',
      match_strength: 'MEDIUM',
      change_type: 'update',
      change_field: 'directors',
      from_val: '2025-11-01',
      to_val: '2026-01-02',
      record_date: '02/01/2026',
    },
    {
      crm_reference: '223344',
      wc1_ref: 'e_tr_wco_22334466',
      crm_name: 'Omar Al-Fahad',
      primary_name: 'Omar Khaled Al-Fahad',
      match_score: '85',
      match_strength: 'MEDIUM',
      change_type: 'update',
      change_field: 'identification',
      from_val: '2025-10-20',
      to_val: '2026-01-03',
      record_date: '03/01/2026',
    },
    {
      crm_reference: '334455',
      wc1_ref: 'e_tr_wco_33445577',
      crm_name: 'Marina Trading Company',
      primary_name: 'Marina International Trading Co',
      match_score: '80',
      match_strength: 'MEDIUM',
      change_type: 'new',
      change_field: 'business_activity',
      from_val: 'N/A',
      to_val: '2026-01-04',
      record_date: '04/01/2026',
    },
    {
      crm_reference: '445566',
      wc1_ref: 'e_tr_wco_44556688',
      crm_name: 'Faisal Al-Suwaidi',
      primary_name: 'Faisal Mohammed Al-Suwaidi',
      match_score: '94',
      match_strength: 'VERY_STRONG',
      change_type: 'update',
      change_field: 'pep_relationship',
      from_val: '2025-12-15',
      to_val: '2026-01-05',
      record_date: '05/01/2026',
    },
    {
      crm_reference: '556677',
      wc1_ref: 'e_tr_wco_55667799',
      crm_name: 'Horizon Capital Partners',
      primary_name: 'Horizon Capital Partners LLC',
      match_score: '77',
      match_strength: 'WEAK',
      change_type: 'update',
      change_field: 'beneficiary',
      from_val: '2025-11-10',
      to_val: '2025-12-28',
      record_date: '28/12/2025',
    },
  ];

  changeLogData.forEach((row) => changeLogSheet.addRow(row));

  // Style header row
  changeLogSheet.getRow(1).font = { bold: true };
  changeLogSheet.getRow(1).fill = {
    type: 'pattern',
    pattern: 'solid',
    fgColor: { argb: 'FFFD7E14' },
  };
  changeLogSheet.getRow(1).font = { bold: true, color: { argb: 'FFFFFFFF' } };

  // Save workbook
  const filePath = path.join(__dirname, '../../../sample-data/screening-list-sample.xlsx');
  await workbook.xlsx.writeFile(filePath);

  console.log('✅ Mock Excel file generated successfully!');
  console.log(`📁 Location: ${filePath}`);
  console.log(`📊 WC Result Sheet: ${wcResultData.length} historical flagged cases`);
  console.log(`📋 Change Log Sheet: ${changeLogData.length} new cases for review`);
}

generateMockExcelData().catch(console.error);
