#!/bin/bash
# AGGRESSIVE CLEANUP - Deletes unnecessary files
echo "🗑️  DELETING UNNECESSARY FILES..."
deleted=0
delete_file() { if [ -f "$1" ]; then rm "$1" && echo "🗑️  $1" && ((deleted++)); fi; }
delete_dir() { if [ -d "$1" ]; then rm -rf "$1" && echo "🗑️  $1/" && ((deleted++)); fi; }

# Root cleanup
delete_file "403_ERROR_FIXED.md"
delete_file "ALL_PHASES_COMPLETE.md"
delete_file "ALL_TESTS_PASSING.md"
delete_file "AUTO_SCREENING_TEST_RESULTS.md"
delete_file "AUTO_SCREENING_WORKING.md"
delete_file "BACKEND_TO_FRONTEND_TODO.md"
delete_file "BLACKLIST_FORMAT_REFERENCE.md"
delete_file "BULK_REVIEW_STATUS.md"
delete_file "BULK_REVIEW_WIZARD_COMPLETE.md"
delete_file "CHANGES_SUMMARY.md"
delete_file "COMPLETE_FEATURES.txt"
delete_file "COMPLETION_CHECKLIST.md"
delete_file "CRITICAL_FIXES.md"
delete_file "DATABASE_STATUS.md"
delete_file "ENV_SETUP.md"
delete_file "FILES_CHANGED.md"
delete_file "FINAL_COMPLETION_SUMMARY.md"
delete_file "FINAL_FIXES.md"
delete_file "FINAL_STATUS.md"
delete_file "FINAL_ULTRA_FLEXIBLE_SUMMARY.md"
delete_file "FIXES_COMPLETE.md"
delete_file "FIX_403_ERROR.md"
delete_file "FIX_SUMMARY.md"
delete_file "FRONTEND_REVIEW_SYSTEM.md"
delete_file "GIT_COMMIT_MESSAGE.md"
delete_file "IMPLEMENTATION_COMPLETE.md"
delete_file "INTEGRATION_COMPLETE.md"
delete_file "LOGBOOK_FIX.md"
delete_file "ORGANIZATION_COMPLETE.md"
delete_file "PARSER_TESTING_RESULTS.md"
delete_file "PHASE10_COMPLETE.md"
delete_file "PHASE2_FINAL_SUMMARY.md"
delete_file "PHASE9_COMPLETE_FIXES.md"
delete_file "QUICK_FIX_SUMMARY.md"
delete_file "QUICK_START.txt"
delete_file "QUICK_START_TEST.md"
delete_file "REVIEW_QUICK_START.md"
delete_file "REVIEW_SYSTEM_GUIDE.md"
delete_file "SAMPLE_DATA_COMPLETE.md"
delete_file "SAMPLE_DATA_GUIDE.md"
delete_file "SCREENER_CHECKER_FIX.md"
delete_file "SCREENING_FIX_COMPLETE.md"
delete_file "SCREENING_QUEUE_FIX.md"
delete_file "SIDE_BY_SIDE_COMPARISON.md"
delete_file "SYSTEM_READY.md"
delete_file "SYSTEM_STATUS.txt"
delete_file "TESTING_GUIDE.md"
delete_file "TEST_RESULTS_SUMMARY.md"
delete_file "TROUBLESHOOTING_403.md"
delete_file "UI_FIXES_COMPLETE.txt"
delete_file "UI_TEXT_FIXED.txt"
delete_file "ULTRA_FLEXIBLE_PARSER.md"
delete_file "UPLOAD_ERROR_FIXED.md"
delete_file "UPLOAD_FIX_COMPLETE.md"
delete_file "UPLOAD_FRONTEND_FIX.md"
delete_file "UPLOAD_SYSTEM_FIXED.md"
delete_file "V2_FIXED_SUMMARY.txt"
delete_file "V2_UPLOAD_FIXED.txt"
delete_file "VISUAL_OVERVIEW.md"
delete_file "WHAT_TO_UPLOAD.md"
delete_file "WHY_403_FORBIDDEN.md"
delete_file "run_tests.sh"
delete_file "test_phase9.sh"
delete_file "test_upload.sh"
delete_file "setup.sh"
delete_dir "node_modules"
delete_file "package.json"
delete_file "package-lock.json"
delete_dir "tests"

# Backend cleanup
cd backend
delete_file "AUTH_COMPLETE.md"
delete_file "AUTH_README.md"
delete_file "PHASE1_COMPLETE.md"
delete_file "PHASE2_COMPLETE.md"
delete_file "PHASE3_GUIDE.md"
delete_file "PHASE4_COMPLETE.md"
delete_file "PHASE5_COMPLETE.md"
delete_file "PHASE6_COMPLETE.md"
delete_file "PHASE7_COMPLETE.md"
delete_file "PHASE8_COMPLETE.md"
delete_file "PHASE8_VERIFICATION_REPORT.md"
delete_file "TEST_CHECKLIST.md"
delete_file "TEST_RESULTS.md"
delete_file "README.md"
delete_file "test_*.py"
delete_file "verify_phase8.py"
delete_file "backup_database.py"
delete_file "check_database.py"
delete_file "debug_login.py"
delete_file "init_database.py"
delete_file "run_migration.py"
delete_file "run_tests.sh"
delete_file "jest.config.js"
delete_file "package.json"
delete_file "tsconfig.json"
delete_file "backend.log"
delete_file "kamco.db"
delete_dir "node_modules"
delete_dir "dist"
delete_dir "src"
delete_dir "venv"
delete_dir ".pytest_cache"
cd ..

# Frontend cleanup
cd frontend
delete_file "ARCHITECTURE.md"
delete_file "PHASE9_COMPLETE.md"
delete_file "PHASE9_PROGRESS.md"
delete_dir "dist"
cd ..

# Organize docs
mkdir -p docs/guides docs/deployment docs/development
[ -f "CREDENTIALS.md" ] && mv "CREDENTIALS.md" "docs/guides/" && echo "✓ Moved CREDENTIALS.md"
[ -f "BACKEND_DEPLOYMENT.md" ] && mv "BACKEND_DEPLOYMENT.md" "docs/deployment/" && echo "✓ Moved BACKEND_DEPLOYMENT.md"
[ -f "QUICK_START.md" ] && mv "QUICK_START.md" "docs/guides/" && echo "✓ Moved QUICK_START.md"
[ -f "PROJECT_ORGANIZATION_SUMMARY.md" ] && mv "PROJECT_ORGANIZATION_SUMMARY.md" "docs/development/" && echo "✓ Moved PROJECT_ORGANIZATION_SUMMARY.md"
[ -f "backend/AUTH_SECURITY_GUIDE.md" ] && mv "backend/AUTH_SECURITY_GUIDE.md" "docs/guides/" && echo "✓ Moved AUTH_SECURITY_GUIDE.md"

echo ""
echo "✨ CLEANUP COMPLETE! Deleted $deleted items"
echo "📁 Organized docs into docs/ folder"
