"""
PDF Generator for Phase 7 - Report Generation
Uses ReportLab to create professional PDF reports with branding
"""
import os
from datetime import datetime
from typing import Dict, Any, List
from io import BytesIO

try:
    from reportlab.lib.pagesizes import letter, A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import inch
    from reportlab.lib import colors
    from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, PageBreak
    from reportlab.platypus import Image as RLImage
    from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
    REPORTLAB_AVAILABLE = True
except ImportError:
    REPORTLAB_AVAILABLE = False
    print("Warning: ReportLab not installed. PDF generation will be limited.")

import logging

logger = logging.getLogger(__name__)


class PDFGenerator:
    """
    PDF report generator using ReportLab
    Creates professional, branded PDF reports with charts and tables
    """
    
    def __init__(self):
        self.reports_dir = "reports"
        os.makedirs(self.reports_dir, exist_ok=True)
        
        if not REPORTLAB_AVAILABLE:
            logger.warning("ReportLab not available - PDF generation disabled")
        
        # Kamco branding colors
        self.primary_color = colors.HexColor('#003366')  # Dark blue
        self.secondary_color = colors.HexColor('#0066CC')  # Medium blue
        self.accent_color = colors.HexColor('#FF6600')  # Orange
        self.success_color = colors.HexColor('#28a745')  # Green
        self.danger_color = colors.HexColor('#dc3545')  # Red
    
    def generate_screening_summary_pdf(
        self,
        data: Dict[str, Any],
        metadata: Dict[str, Any]
    ) -> str:
        """
        Generate PDF for screening summary report
        
        Args:
            data: Report data
            metadata: Report metadata
            
        Returns:
            File path
        """
        if not REPORTLAB_AVAILABLE:
            raise ImportError("ReportLab is required for PDF generation. Install with: pip install reportlab")
        
        filename = f"screening_summary_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
        filepath = os.path.join(self.reports_dir, filename)
        
        # Create PDF document
        doc = SimpleDocTemplate(filepath, pagesize=letter)
        story = []
        styles = getSampleStyleSheet()
        
        # Custom styles
        title_style = ParagraphStyle(
            'CustomTitle',
            parent=styles['Heading1'],
            fontSize=24,
            textColor=self.primary_color,
            spaceAfter=30,
            alignment=TA_CENTER
        )
        
        heading_style = ParagraphStyle(
            'CustomHeading',
            parent=styles['Heading2'],
            fontSize=16,
            textColor=self.primary_color,
            spaceAfter=12,
            spaceBefore=12
        )
        
        # Cover page
        story.append(Spacer(1, 2*inch))
        story.append(Paragraph("Kamco Investment Company", title_style))
        story.append(Paragraph(metadata.get('title', 'Screening Summary Report'), title_style))
        story.append(Spacer(1, 0.5*inch))
        
        # Metadata
        meta_data = [
            ['Generated:', metadata.get('generated_at', '')],
            ['Generated By:', metadata.get('generated_by', '')],
            ['Report Period:', f"{metadata.get('date_from', 'N/A')} to {metadata.get('date_to', 'N/A')}"],
            ['Total Records:', str(data.get('total_screenings', 0))]
        ]
        
        meta_table = Table(meta_data, colWidths=[2*inch, 4*inch])
        meta_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (0, -1), colors.lightgrey),
            ('TEXTCOLOR', (0, 0), (-1, -1), colors.black),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 12),
            ('GRID', (0, 0), (-1, -1), 1, colors.grey)
        ]))
        
        story.append(meta_table)
        story.append(PageBreak())
        
        # Executive Summary
        story.append(Paragraph("Executive Summary", heading_style))
        story.append(Spacer(1, 0.2*inch))
        
        # Key metrics table
        metrics_data = [
            ['Metric', 'Value'],
            ['Total Screenings', str(data.get('total_screenings', 0))],
            ['Total Matches', str(data.get('total_matches', 0))],
            ['Critical Matches', str(data.get('critical_matches', 0))],
            ['High Risk Matches', str(data.get('high_matches', 0))],
            ['Medium Risk Matches', str(data.get('medium_matches', 0))],
            ['Low Risk Matches', str(data.get('low_matches', 0))],
            ['Match Rate', f"{data.get('match_rate', 0)}%"]
        ]
        
        metrics_table = Table(metrics_data, colWidths=[3*inch, 2*inch])
        metrics_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), self.primary_color),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 12),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 12),
            ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
            ('GRID', (0, 0), (-1, -1), 1, colors.black)
        ]))
        
        story.append(metrics_table)
        story.append(Spacer(1, 0.3*inch))
        
        # Entity breakdown
        story.append(Paragraph("Entity Type Breakdown", heading_style))
        entity_breakdown = data.get('entity_breakdown', {})
        
        if entity_breakdown:
            entity_data = [['Entity Type', 'Count']]
            for entity_type, count in entity_breakdown.items():
                entity_data.append([entity_type.capitalize(), str(count)])
            
            entity_table = Table(entity_data, colWidths=[3*inch, 2*inch])
            entity_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), self.secondary_color),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
                ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, 0), 11),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 10),
                ('GRID', (0, 0), (-1, -1), 1, colors.black)
            ]))
            
            story.append(entity_table)
        
        story.append(PageBreak())
        
        # Top blacklist matches
        story.append(Paragraph("Top Blacklist Matches", heading_style))
        top_matches = data.get('top_blacklist_matches', [])[:10]
        
        if top_matches:
            match_data = [['Blacklist Name', 'Source', 'Match Count', 'Avg Score']]
            for match in top_matches:
                match_data.append([
                    match.get('name', 'N/A')[:40],  # Truncate long names
                    match.get('source', 'N/A'),
                    str(match.get('count', 0)),
                    f"{match.get('avg_score', 0):.1f}"
                ])
            
            match_table = Table(match_data, colWidths=[2.5*inch, 1.5*inch, 1*inch, 1*inch])
            match_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), self.primary_color),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
                ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, 0), 10),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
                ('GRID', (0, 0), (-1, -1), 1, colors.black)
            ]))
            
            story.append(match_table)
        
        # Footer
        story.append(Spacer(1, 0.5*inch))
        footer_style = ParagraphStyle('Footer', parent=styles['Normal'], fontSize=8, textColor=colors.grey)
        story.append(Paragraph(
            f"Generated by Kamco AML/CFT System on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
            footer_style
        ))
        story.append(Paragraph("CONFIDENTIAL - For Internal Use Only", footer_style))
        
        # Build PDF
        doc.build(story)
        logger.info(f"PDF report generated: {filepath}")
        return filepath
    
    def generate_flagged_items_pdf(
        self,
        data: Dict[str, Any],
        metadata: Dict[str, Any]
    ) -> str:
        """Generate PDF for flagged items report"""
        if not REPORTLAB_AVAILABLE:
            raise ImportError("ReportLab is required for PDF generation")
        
        filename = f"flagged_items_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
        filepath = os.path.join(self.reports_dir, filename)
        
        doc = SimpleDocTemplate(filepath, pagesize=letter)
        story = []
        styles = getSampleStyleSheet()
        
        # Title
        title_style = ParagraphStyle('Title', parent=styles['Heading1'], fontSize=20, textColor=self.primary_color, alignment=TA_CENTER)
        story.append(Paragraph("Flagged Items Report", title_style))
        story.append(Spacer(1, 0.3*inch))
        
        # Summary metrics
        summary_data = [
            ['Metric', 'Value'],
            ['Total Flagged', str(data.get('total_flagged', 0))],
            ['Pending', str(data.get('pending_count', 0))],
            ['Approved', str(data.get('approved_count', 0))],
            ['Rejected', str(data.get('rejected_count', 0))],
            ['Resolved', str(data.get('resolved_count', 0))],
            ['Avg Resolution Time', f"{data.get('average_resolution_time', 0)} days"]
        ]
        
        summary_table = Table(summary_data, colWidths=[3*inch, 2*inch])
        summary_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), self.danger_color),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('GRID', (0, 0), (-1, -1), 1, colors.black)
        ]))
        
        story.append(summary_table)
        story.append(PageBreak())
        
        # Flagged items details (first 20)
        flagged_items = data.get('flagged_items', [])[:20]
        if flagged_items:
            story.append(Paragraph("Flagged Items Details (Top 20)", styles['Heading2']))
            story.append(Spacer(1, 0.2*inch))
            
            items_data = [['Entity Name', 'Type', 'Status', 'Severity', 'Flagged By']]
            for item in flagged_items:
                items_data.append([
                    item.get('kamco_name', 'N/A')[:30],
                    item.get('kamco_type', 'N/A'),
                    item.get('status', 'N/A'),
                    item.get('severity', 'N/A'),
                    item.get('flagged_by', 'N/A')
                ])
            
            items_table = Table(items_data, colWidths=[2*inch, 1*inch, 1*inch, 1*inch, 1.5*inch])
            items_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), self.primary_color),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, -1), 9),
                ('GRID', (0, 0), (-1, -1), 1, colors.black)
            ]))
            
            story.append(items_table)
        
        doc.build(story)
        logger.info(f"PDF report generated: {filepath}")
        return filepath
    
    def generate_case_history_pdf(
        self,
        data: Dict[str, Any],
        metadata: Dict[str, Any]
    ) -> str:
        """Generate PDF for case history report"""
        if not REPORTLAB_AVAILABLE:
            raise ImportError("ReportLab is required for PDF generation")
        
        filename = f"case_history_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
        filepath = os.path.join(self.reports_dir, filename)
        
        doc = SimpleDocTemplate(filepath, pagesize=letter)
        story = []
        styles = getSampleStyleSheet()
        
        # Title
        title_style = ParagraphStyle('Title', parent=styles['Heading1'], fontSize=20, textColor=self.primary_color, alignment=TA_CENTER)
        story.append(Paragraph("Case History Report", title_style))
        story.append(Spacer(1, 0.3*inch))
        
        # Summary
        summary_data = [
            ['Metric', 'Value'],
            ['Total Cases', str(data.get('total_cases', 0))],
            ['Open Cases', str(data.get('open_cases', 0))],
            ['Closed Cases', str(data.get('closed_cases', 0))],
            ['Approved', str(data.get('approved_cases', 0))],
            ['Rejected', str(data.get('rejected_cases', 0))],
            ['Avg Resolution Time', f"{data.get('average_resolution_time', 0)} days"],
            ['SLA Compliance', f"{data.get('sla_compliance_rate', 0)}%"]
        ]
        
        summary_table = Table(summary_data, colWidths=[3*inch, 2*inch])
        summary_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), self.success_color),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('GRID', (0, 0), (-1, -1), 1, colors.black)
        ]))
        
        story.append(summary_table)
        
        doc.build(story)
        logger.info(f"PDF report generated: {filepath}")
        return filepath
    
    def generate_compliance_audit_pdf(
        self,
        data: Dict[str, Any],
        metadata: Dict[str, Any]
    ) -> str:
        """Generate PDF for compliance audit report"""
        if not REPORTLAB_AVAILABLE:
            raise ImportError("ReportLab is required for PDF generation")
        
        filename = f"compliance_audit_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
        filepath = os.path.join(self.reports_dir, filename)
        
        doc = SimpleDocTemplate(filepath, pagesize=letter)
        story = []
        styles = getSampleStyleSheet()
        
        # Title
        title_style = ParagraphStyle('Title', parent=styles['Heading1'], fontSize=20, textColor=self.primary_color, alignment=TA_CENTER)
        story.append(Paragraph("Compliance Audit Report", title_style))
        story.append(Spacer(1, 0.3*inch))
        
        # Summary
        summary_data = [
            ['Metric', 'Value'],
            ['Total Actions', str(data.get('total_actions', 0))],
            ['Blacklist Changes', str(data.get('blacklist_changes', 0))],
            ['Screenings Performed', str(data.get('screenings_performed', 0))],
            ['Decisions Made', str(data.get('decisions_made', 0))],
            ['Compliance Score', f"{data.get('compliance_score', 0)}%"]
        ]
        
        summary_table = Table(summary_data, colWidths=[3*inch, 2*inch])
        summary_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), self.primary_color),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('GRID', (0, 0), (-1, -1), 1, colors.black)
        ]))
        
        story.append(summary_table)
        
        doc.build(story)
        logger.info(f"PDF report generated: {filepath}")
        return filepath


def get_pdf_generator() -> PDFGenerator:
    """Get PDF generator instance"""
    return PDFGenerator()
